name: epc
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

workspace:
  - apps/quiz
  - packages/monetization
  - packages/core
  - packages/auth
  - packages/ai

dev_dependencies:
  melos: ^7.4.0

melos:
  scripts:
    setup_all:
      run: melos exec -- flutter clean && melos bootstrap
    setup:auth:
      run: melos exec -c 1 --scope=auth -- flutter clean && flutter pub get && flutter analyze
    setup:core:
      run: melos exec -c 1 --scope=core -- flutter clean && flutter pub get && flutter analyze
    setup:quiz_generator:
      run: melos exec -c 1 --scope=quiz_generator -- flutter clean && flutter pub get && flutter analyze
    setup:monetization:
      run: melos exec -c 1 --scope=monetization -- flutter clean && flutter pub get && flutter analyze
    bootstrap:
      run: melos bootstrap