name: auth
resolution: workspace
description: Authentication package for EPC monorepo
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.10.7"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  url_launcher: ^6.3.1
  crypto: ^3.0.5
  http: ^1.5.0
  flutter_secure_storage: ^10.0.0
  purchases_flutter: ^9.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter
