name: ai
description: AI integrations and strategies
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.10.7"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
