name: core
description: Core shared logic and utilities
version: 0.0.1
resolution: workspace
publish_to: none

environment:
  sdk: "^3.10.7"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1

  cli_table: ^1.0.2

  flutter_dotenv: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^3.2.4
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
